Resources:
  CustomResourceServerLambda:
    Metadata:
      Source: https://github.com/tobilg/cfn-custom-resource-server
      Version: 0.1.0
    Properties:
      Code:
        ZipFile: |
$SOURCE
      Description: Cloudformation custom resource for Cognito Resource Servers
      Handler: index.handler
      Role: 
        Fn::GetAtt: 
          - CustomResourceServerLambdaExecutionRole
          - Arn
      Runtime: nodejs10.x
      Timeout: 30
    Type: AWS::Lambda::Function
  CustomResourceServerLambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Action:
              - sts:AssumeRole
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - arn:aws:iam::aws:policy/service-role/AWSLambdaRole
      Policies:
        - PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - cognito-idp:CreateResourceServer
                  - cognito-idp:UpdateResourceServer
                  - cognito-idp:DeleteResourceServer
                Resource:
                  - 'Fn::Join':
                    - ':'
                    - - 'arn:aws:cognito-idp'
                      - Ref: 'AWS::Region'
                      - Ref: 'AWS::AccountId'
                      - 'userpool/*'
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource:
                  - 'Fn::Join':
                    - ':'
                    - - 'arn:aws:logs'
                      - Ref: 'AWS::Region'
                      - Ref: 'AWS::AccountId'
                      - 'log-group:/aws/lambda/*:*:*'
          PolicyName:
            'Fn::Join':
              - '-'
              - - 'CustomResourceServerLambdaExecutionPolicy'
                - Ref: 'AWS::StackName'
    